name: firstmangroup_flutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  delayed_display: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sp1.png
    - assets/sp2.png
    - assets/sp3.png
    - assets/spa.png
    - assets/in1.png
    - assets/in2.png
    - assets/in3.png
    - assets/right.png
    - assets/bnner1.png
    - assets/rightarrow.png
    - drawable/aboutbg.png
    - drawable/add.png
    - drawable/add_banner.png
    - drawable/add_new_icon.png
    - drawable/addlisting.png
    - drawable/addproperty.png
    - drawable/agent.png
    - drawable/amount.png
    - drawable/annoucements.png
    - drawable/app_icon.png
    - drawable/app_new_icon.png
    - drawable/app_noti_icon.png
    - drawable/area.png
    - drawable/area_one.png
    - drawable/attendes.png
    - drawable/back_black.png
    - drawable/badge.png
    - drawable/ban_inven.png
    - drawable/bank.png
    - drawable/banner.jpg
    - drawable/bathrooms.png
    - drawable/bed.png
    - drawable/bhk.png
    - drawable/bhk_one.png
    - drawable/bin.png
    - drawable/bnner1.png
    - drawable/boost.png
    - drawable/brochure.png
    - drawable/budget.png
    - drawable/budget_pro.png
    - drawable/cafe.png
    - drawable/cal_imgg.png
    - drawable/calendar.png
    - drawable/callfill.png
    - drawable/callus.png
    - drawable/car.png
    - drawable/cartype.png
    - drawable/carwhite.png
    - drawable/ccc.png
    - drawable/cctv.png
    - drawable/checkeligibility.png
    - drawable/checkoff.png
    - drawable/checkoff1.png
    - drawable/checkon.png
    - drawable/checkon1.png
    - drawable/childres_area.png
    - drawable/chips_bag.png
    - drawable/circle_fill.png
    - drawable/circle_stroke.png
    - drawable/circlearrows.png
    - drawable/circleblue.png
    - drawable/circleorange.png
    - drawable/close.png
    - drawable/club_house.png
    - drawable/commission.png
    - drawable/commission_act.png
    - drawable/commissions.png
    - drawable/contact_rm.png
    - drawable/contactrm.png
    - drawable/contactrm_white.png
    - drawable/date.png
    - drawable/delete.png
    - drawable/demo_one.png
    - drawable/demo_two.png
    - drawable/demo_three.png
    - drawable/down_arr.png
    - drawable/down_arrow.png
    - drawable/downarrow.png
    - drawable/download.png
    - drawable/edit.png
    - drawable/edit_blue.png
    - drawable/edit_pro_background.png
    - drawable/email.png
    - drawable/email_icon.png
    - drawable/emi_calcu.png
    - drawable/emicalculator.png
    - drawable/emicalculator_white.png
    - drawable/eve_anima.png
    - drawable/eve_date.png
    - drawable/eve_location.png
    - drawable/eve_time.png
    - drawable/event_attend.png
    - drawable/event_icon.png
    - drawable/eventss.png
    - drawable/ex_track_lead.png
    - drawable/exclusae.png
    - drawable/extra_add_listing.png
    - drawable/extra_short_list.png
    - drawable/extra_site_visit.png
    - drawable/eye.png
    - drawable/eye_blue.png
    - drawable/faq.png
    - drawable/personal_page.png
    - drawable/terms_checked.png
    - drawable/menu.png
    - drawable/home.png
    - drawable/home_act.png
    - drawable/sales_list.png
    - drawable/sales_list_act.png
    - drawable/my_office.png
    - drawable/my_office_act.png
    - drawable/select_city.png
    - drawable/select_city_fill.png
    - drawable/realestate_back.png
    - drawable/searchhouse.png
    - drawable/fmnet.png
    - drawable/tracklead.png
    - drawable/invfm.png
    - drawable/offers.png
    - drawable/notification_new.png
    - drawable/green_on.png
    - drawable/logout.png
    - drawable/user_pro.png
    - drawable/kyc.png
    - drawable/tpnetwork.png
    - drawable/my_listingss.png
    - drawable/premiumcalculator.png
    - drawable/loaneligibility.png
    - drawable/inviteba.png
    - drawable/terms.png
    - drawable/map_location.png
    - drawable/map.png
    - drawable/whatsapp_new.png
    - drawable/user.png
    - drawable/phone.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Gotham
       fonts:
         - asset: fonts/GothamRounded_Book.otf
     - family: GothamLight
       fonts:
         - asset: fonts/GothamRounded_Light.otf
     - family: GothamMedium
       fonts:
         - asset: fonts/GothamRounded_Medium.otf




  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
